#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.1
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 10

# sketchybar integration
# EXTERNAL_BAR_HEIGHT=$(sketchybar --query bar | jq ".height") + 7
yabai -m config external_bar all:0:46
#
# yabai -m space 1 --label chat
# yabai -m space 2 --label code
# yabai -m space 3 --label terminal
# yabai -m space 4 --label browser
# yabai -m space 5 --label tools
# yabai -m space 6 --label email

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^.*Rider.*$" title="^(Welcome.|Rename|Pull Members Up|Copy Type|Extract Method|Safe Delete)*$" manage=off
yabai -m rule --add app="^Sublime Merge$" title="^Merge Tool$" manage=off
yabai -m rule --add app="^Hammerspoon$" title="^Hammerspoon Console$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off

# apps placement to space
yabai -m rule --add app="^(Slack|WhatsApp|Microsoft Teams|Telegram)$" space=chat
yabai -m rule --add app="^(IntelliJ IDEA|WebStorm|RubyMine|PyCharm|.*Rider.*)$" space=code
yabai -m rule --add app="^(kitty)$" space=terminal
yabai -m rule --add app="^(Google Chrome|Firefox)$" space=browser
yabai -m rule --add app="^(DataGrip|Docker|Postman|Sublime Merge)$" space=tools
yabai -m rule --add app="^(Microsoft Outlook|Mail)$" space=email

echo "yabai configuration loaded.."
