#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config window_origin_display default
yabai -m config window_placement second_child

# floating windows are always on top (default: off)
yabai -m config window_topmost off
yabai -m config window_shadow off

yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.1
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config window_border_radius 0
yabai -m config active_window_border_color 0xffEBDBB2
yabai -m config normal_window_border_color 0xff
yabai -m config insert_feedback_color 0xffd75f5f

yabai -m config auto_balance on
# with auto_balance off split_ratio doesnt work
# yabai -m config split_ratio 0.50

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

# sketchybar integration
# EXTERNAL_BAR_HEIGHT=$(sketchybar --query bar | jq ".height") + 7
yabai -m config external_bar all:0:46

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^.*Rider.*$" title="^(Welcome.|Rename|Pull Members Up|Copy Type|Extract Method|Safe Delete)*$" manage=off
yabai -m rule --add app="^Sublime Merge$" title="^Merge Tool$" manage=off
yabai -m rule --add app="^Hammerspoon$" title="^Hammerspoon Console$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Simulator" app="^Simulator$" manage=off

# apps placement to space
yabai -m rule --add app="^(Slack|WhatsApp|Microsoft Teams|Telegram)$" space=chat
yabai -m rule --add app="^(IntelliJ IDEA|WebStorm|RubyMine|PyCharm|.*Rider.*)$" space=code
yabai -m rule --add app="^(kitty)$" space=terminal
yabai -m rule --add app="^(Google Chrome|Firefox)$" space=browser
yabai -m rule --add app="^(DataGrip|Docker|Postman|Sublime Merge)$" space=tools
yabai -m rule --add app="^(Microsoft Outlook|Mail)$" space=email

# There's still a slight mistake in there: The event=application_launched signal does not carry $YABAI_WINDOW_ID, which then evaluates to an empty string in the signals action, causing it to act on the focused window.
# If multiple windows are restored, this is incorrect behavior.
# Instead, you should use the $YABAI_PROCESS_ID that the signal actually carries and query for all windows, filtering by their process id to get their window id, and then change the split on that.

# yabai -m signal --add \
# 	label=launch-split \
# 	event=application_launched \
# 	action='~/.config/yabai/auto-split.sh'
#
# yabai -m signal --add \
# 	label=create-split \
# 	event=window_created \
# 	action='~/.config/yabai/auto-split.sh'

echo "yabai configuration loaded.."
