#!/usr/bin/env sh

#if sudo stops working read there
#https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

yabai -m signal --add event=dock_did_restart action="yabai"

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config window_origin_display default
yabai -m config window_placement second_child

# floating windows are always on top (default: off)
yabai -m config window_topmost off
yabai -m config window_shadow off

yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.1
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config window_border_radius 0
yabai -m config active_window_border_color 0xffEBDBB2
yabai -m config normal_window_border_color 0xff
yabai -m config insert_feedback_color 0xffd75f5f

yabai -m config auto_balance on
# with auto_balance off split_ratio doesnt work
# yabai -m config split_ratio 0.50

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

yabai -m config external_bar all:0:0

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="JetBrains Rider" title="^(Welcome.|Rename|Pull Members Up|Copy Type|Extract Method|Safe Delete|Extract Interface)*$" manage=off
yabai -m rule --add app="JetBrains Rider" title="Rename" manage=off
yabai -m rule --add app="Microsoft AutoUpdate" title="Microsoft AutoUpdate" manage=off
yabai -m rule --add app="^Sublime Merge$" title="^Merge Tool$" manage=off
yabai -m rule --add app="JetBrains Toolbox" manage=off
yabai -m rule --add app="^Hammerspoon$" title="^Hammerspoon Console$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Simulator" app="^Simulator$" manage=off
yabai -m rule --add label="Abacus" app="^Abacus$" title="Selection list - Project" manage=off

# android studio emulator dropdown
yabai -m rule --add app="^qemu-system-aarch64$" manage=off

# default spaces
yabai -m space 1 --label chat
yabai -m space 2 --label code
yabai -m space 3 --label three
yabai -m space 4 --label browser
yabai -m space 5 --label email
yabai -m space 6 --label tools

# apps placement to space
yabai -m rule --add app="^(Slack|WhatsApp|Microsoft Teams|Telegram)$" space=chat
yabai -m rule --add app="^(IntelliJ IDEA|WebStorm|RubyMine|PyCharm|.*Rider.*)$" space=code
yabai -m rule --add app="^(kitty)$" space=terminal
yabai -m rule --add app="^(Google Chrome|Firefox)$" space=browser
yabai -m rule --add app="^(Microsoft Outlook|Mail)$" space=email
yabai -m rule --add app="^(DataGrip|Docker|Postman|Sublime Merge)$" space=tools

echo "yabai configuration loaded.."
