local r = require("lt.utils.remaps")
local builtin = require("telescope.builtin")
local functions = require("lt.plugins.telescope.functions")

r.noremap("n", "<leader>pp", "<cmd>Telescope projects<CR>", "Projects")
r.noremap("n", "<leader>ps", builtin.live_grep, "Live grep")
r.noremap("n", "<leader>pS", functions.live_grep_in_folder, "Live grep in folder")
r.noremap("n", "<leader>pf", builtin.find_files, "Find files")
r.noremap("n", "<leader>po", builtin.oldfiles, "Find files")
r.noremap("n", "<leader>pg", builtin.git_files, "Find git files")
r.noremap("n", "<leader>cc", functions.search_config, "Search neovim config")
r.noremap("n", "<leader>/h", builtin.highlights, "Search highlights")
r.noremap("n", "<leader>/C", builtin.command_history, "Search command history")
r.noremap("n", "<leader>/c", builtin.commands, "Search commands")
r.noremap("n", "<leader>/r", builtin.registers, "Search registers")
r.noremap("n", "<leader>/m", builtin.marks, "Search marks")
r.noremap("n", "<leader>/M", builtin.keymaps, "Search keymaps")
r.noremap("n", "<leader>/t", builtin.treesitter, "Search treesitter")
r.noremap("n", "<leader>/gb", builtin.git_branches, "Search git branches")
r.noremap("n", "<leader>/gc", builtin.git_commits, "Search git commits")
r.noremap("n", "<leader>bl", builtin.buffers, "Search buffers")
r.noremap("n", "<leader>bc", builtin.git_bcommits, "Search buffer git commits")
