#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

export ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
export PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

export FONT="SF Pro"                                                 # Needs to have Regular, Bold, Semibold, Heavy and Black variants
export ICON_FONT="Font Awesome 5 Pro:Regular:16.0"                       # Needs to have Regular, Bold, Semibold, Heavy and Black variants
export SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=3 # All paddings use this value (icon, label, background)

export POPUP_BORDER_WIDTH=2
export POPUP_CORNER_RADIUS=11

SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar height=39 \
	color="$BAR_COLOR" \
	shadow=$SHADOW \
	position=bottom \
	sticky=on \
	padding_right=$((10 - PADDINGS)) \
	padding_left=18 \
	corner_radius=9 \
	y_offset=3 \
	margin=0 \
	blur_radius=20 \
	notch_width=0 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:14.0" \
	icon.color="$ICON_COLOR" \
	icon.padding_left=$PADDINGS \
	icon.padding_right=$PADDINGS \
	label.font="$FONT:Semibold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left=$PADDINGS \
	label.padding_right=$PADDINGS \
	background.padding_right=$PADDINGS \
	background.padding_left=$PADDINGS \
	popup.background.border_width=2 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/wake.sh"
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center

# Right
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/wifi.sh"

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
