#!/bin/bash

#
# git nuke <branch-name>
#
# Delete a branch (irrespective of its merged status) and
# remove from origin.
#

if [ -z $1 ] ; then
    echo "Branch Needed";
    exit 1
fi

read -p "Are you want to nuke: $1 (y/n)?" CONT

if [ "$CONT" = "n" ]; then
    echo Aborting
    exit 1
fi

if git show-branch "$1" > /dev/null 2>&1
then
    git branch -D "$1"
else
    echo "No local branch to delete"
fi

git remote prune origin
if git show-branch "origin/$1" > /dev/null 2>&1
then
    echo "Deleting remote $1 ..."
    git push origin ":$1"
else
    echo "No remote branch to delete"
fi