#!/bin/bash

ICON="$1"
CANCEL_ICON=""
CONFIRM_ICON=""

case "$(echo -e "$CANCEL_ICON\n$CONFIRM_ICON" | rofi -dmenu -theme confirmation_dialog -mesg "$ICON")" in
    $CANCEL_ICON$)  exit 1;;
    $CONFIRM_ICON) exit 0;;
esac

exit 1

